# Site settings
title: Irfan Yasin
email: hello@irfanyasin.com
author: Irfan Yasin
description: "Personal blog of Irfan Yasin, Developer"
baseurl: ""
url: "http://irfanyasin.com"

# Build settings
markdown: redcarpet2
permalink: pretty
paginate: 3
